# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

dbd:
    type: mariadb:10.4
    disk: 2048
files:
  type: network-storage:1.0
  disk: 256
